name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm install
      - name: Deploy to GH Pages
        run: |
          git config --global user.email ${{seacrets.EMAIL}}
          git config --global user.name ${{seacrets.USERNAME}}
          git remote set-url origin https://${{seacrets.PERSONAL_TOKEN}}@github.com/${{seacrets.USERNAME}}/github_actions_test>.git
          npm run deploy
